# Render deployment configuration for Pokemon API
services:
  - type: web
    name: pokemon-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: QDRANT_API_KEY
        sync: false  # You'll set this in Render dashboard
      - key: QDRANT_URL
        sync: false  # You'll set this in Render dashboard
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /health
    plan: free  # Use free tier
